# Licensed under the Apache License, Version 2.0.
FROM gcr.io/distroless/static@sha256:e2e927ec666bae08560abb3c55d0659eceabb657f56b6782ab500a9fc7f555e3
COPY bin/cluster-autoscaler /cluster-autoscaler
WORKDIR /
ENTRYPOINT ["/cluster-autoscaler"]
